
# tap repositories and their packages

tap caskroom/cask
cask charles
cask dropbox
cask functionflip
cask google-chrome
cask kaleidoscope
cask mongochef
cask mongodb-compass
cask skitch
cask virtualbox
cask vlc

# tap getantibody/antibody
# brew antibody

tap homebrew/aliases
tap homebrew/bundle
tap homebrew/completions

tap homebrew/core
brew autoconf
brew boost
brew buku
brew c-ares
brew cask
brew cmake
brew coreutils
brew direnv
# brew docker
brew findutils
brew gdbm
brew git
brew grc
brew highlight
brew httpie
brew jo
brew libwebsockets
brew lua
brew mackup
brew makedepend
brew mas
brew miller
brew mongodb
brew mr
brew node-build
brew nodenv
brew openssl
brew pcre
brew pkg-config
brew putty
brew python3
brew rbenv
brew readline
brew renameutils
brew ruby-build
brew sphinx-doc
brew sqlite
brew squid
brew wget
brew xz
brew yadm
# brew zsh

tap homebrew/dupes
tap homebrew/versions
tap nodenv/nodenv

brew nodenv-npm-migrate
brew nodenv-package-json-engine
brew nodenv-package-rehash
brew nodenv-update

tap rcmdnk/file
brew brew-file

# Below applications were installed by Cask,
# but do not have corresponding casks.

# App Store applications
appstore 937984704 Amphetamine
appstore 417375580 BetterSnapTool
appstore 969418666 ColorSnapper2
appstore 409183694 Keynote
appstore 926036361 LastPass
appstore 409203825 Numbers
appstore 409201541 Pages
appstore 967805235 Paste
appstore 425424353 The Unarchiver
